before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
    goamd64:
      - v2
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
archives:
  - replacements:
      darwin: macos
      amd64: x86_64
      386: x86
    format_overrides:
      - goos: windows
        format: zip
signs:
  - cmd: ssh-file-sign
    args: ["${artifact}", "${signature}"]
    artifacts: checksum
release:
  prerelease: auto
milestones:
  - close: true
