before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - id: reproducible
    flags:
      - -trimpath
    ldflags:
      - -s -w
	env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
    goamd64:
      - v2
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'
universal_binaries:
  - id: universal
    ids:
    - reproducible
archives:
  - id: reproducible
    builds:
      - reproducible
    name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
signs:
  - cmd: ssh-file-sign
    args: ["${artifact}", "${signature}"]
    artifacts: checksum
release:
  prerelease: auto
milestones:
  - close: true
